### ISSUE TITLE
Cropping of live map

### ISSUE THREAD

**Issue by Foxi352** [And3rsL/Deebotozmo#2]
Congratulations for live map in latest release !
Works good, but cropping seems not yet to be working correctly ...

`<img src="data:image/;base64,{{ p.livemap | safe }}" style="border: 1px solid red;">`

![Screenshot 2020-05-20 at 14 28 26](https://user-images.githubusercontent.com/5746932/82446040-2e48e800-9aa6-11ea-96e2-6cd9c0388bf8.png)

**Comment by And3rsL** [comment]
You right i forgot a debug line
https://github.com/And3rsL/Deebotozmo/blob/b88e4c6bcd206518caf75213fd48ceb5ac20bbf7/deebotozmo/map.py#L93

Fix it asap

**Comment by Foxi352** [comment]
I am completely not into Deebot as i got mine only 1 week ago. But i will for sure dig deeper into the code once my smarthome integration is working (i wrote you an email concerning events for this. That's me :-) )

Should i even find something interesting that's not yet covered by your lib i will for sure come back to you :D

**Comment by And3rsL** [comment]
Got room colors and things position X,Y

Please if you can test it :)

**Comment by Foxi352** [comment]
I will test more in detail tomorrow. But from a quick test i have the following error.
```
Exception in thread schedule_thread_livemap:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/swagener/.local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 518, in refresh_liveMap
    self.live_map = self.Map.GetBase64Map()
  File "/home/swagener/.local/lib/python3.8/site-packages/deebotozmo/map.py", line 174, in GetBase64Map
    robot_icon = Image.open("robot.png")
  File "/home/swagener/.local/lib/python3.8/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'robot.png'

```

**Comment by And3rsL** [comment]
Yes, i want to keep maps things inside map class.

 i currently try to find the best Memory optimization, my Raspberry seems to crash when rooms are draw

**Comment by Foxi352** [comment]
Sounds right to move map into map class. As i am only developing our plugin code breaking changes are not a problem. 

I am on 1.5.4 now. png not found error seems to have gone. But i have a white image.

Here is the Base64 string i get for live_map:
```
iVBORw0KGgoAAAANSUhEUgAAA+gAAAPoCAYAAABNo9TkAAAPPElEQVR4nO3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIB3AxB7AAGF3vmMAAAAAElFTkSuQmCC 

```

**Comment by And3rsL** [comment]
Should work now

**Comment by Foxi352** [comment]
Yes, working great !! Thank you !

Quick question: if the instance is created with `monitor=True` should the variables like `live_map` be updated automatically every X seconds, or do i have to still manually call a `refresh_liveMap()` ?

![Screenshot 2020-05-26 at 17 35 20](https://user-images.githubusercontent.com/5746932/82920204-4a053000-9f77-11ea-8f8d-d4c7772e18f8.png)

**Comment by And3rsL** [comment]
> Yes, working great !! Thank you !
> 
> Quick question: if the instance is created with `monitor=True` should the variables like `live_map` be updated automatically every X seconds, or do i have to still manually call a `refresh_liveMap()` ?
> 
> ![Screenshot 2020-05-26 at 17 35 20](https://user-images.githubusercontent.com/5746932/82920204-4a053000-9f77-11ea-8f8d-d4c7772e18f8.png)

its old settings left over from sucks library, it didnt work too well and i disabled it.. i need to find a new way to refresh components automatically. i will open a new issue just to remember

**Comment by Foxi352** [comment]
Since you disabled it it doesn't do a first poll after having connected. So i have to add a request_all_statuses() in my run method to get initial status on startup. Just for information / reference, everything is ok :-)

```
self.vacbot.connect_and_wait_until_ready()
self.iotProduct = self.getIotProduct()
self.vacbot.request_all_statuses()
```

**Comment by Morg42** [comment]
Hi, as a new user - both to my Ozmo 950 as well as to the library ;) - I start hitting issues, not sure if this is related to the software or to me ;)

I tried using the cli both of the current GitHub version as well as the one installed with pip (1.6.0).

Running deebotozmo exportlivemap map.png results in a 1,5 MB PNG with a size of 19200x19200 px, the actual map is in the bottom left corner approx. 600 x 700 px large.

Do I need to do something different? I haven't completely absorbed the map code and wanted to ask before I'm gone 2 days into the code ;)

[map.log](https://github.com/And3rsL/Deebotozmo/files/4700894/map.log)

**Comment by Foxi352** [comment]
@Morg42 Do you see the correct livemap when using the SHNG plugin ? Because the library is the same. If it works in SHNG it is probably a CLI issue.

PS: If you pull the latest plugin code, you should see a real "live" livemap updated +/- every 5 seconds while your bot is cleaning ...

**Comment by Morg42** [comment]
shng plugin works fine, also live image update.

I plan on digging into the map functions (display, "georef", divide and join rooms); for this I need an easy way to plot rooms from coordinates from the command line. So I tried the cli... ;)

**Comment by And3rsL** [comment]
I don't see any error by logs.. it might be a cropping issue . Default map size is 6400 and resize factor is 3, so 19200 is the image uncropped

**Comment by Morg42** [comment]
As of today, the plugin also yields the same "mini-map" in a 19200x19200 canvas. The livemap-String is zipped in the attachment
[livemap.zip](https://github.com/And3rsL/Deebotozmo/files/4705593/livemap.zip)

**Comment by Morg42** [comment]
No, there are no errors. Can you give me a hint where cropping is done, I'll try to find something

**Comment by And3rsL** [comment]
i think because room colors just paint outside the room and this cause cropping issues.. i added a option to disable room colors. try it out

**Comment by Morg42** [comment]
Works fine now :)

Something else in regard to cropping: today I tried working on multi-storey maps and cleaning. After changing the storey, if a new map is created, this  new map is overlaid onto the old one, so the outer regions show the remainder of the old map. I think on refreshing the map only the newly-supplied regions are repainted and the remaining canvas stays untouched...right? So if the new map is smaller than the old one - which it almost always will be on creating a new map -, there can't be an update for the "outer space" regions ;)

Do you happen to know if this can be detected / handled? I guess only if the device "tells" you about creating a new map or something like this.

Trying to find something in the log did not prove successful, though I might have overlooked some subtle hint. 

I don't think this is of high importance or let alone urgent, just to let you know. Maybe some day someone finds a way to address this. I will try to change maps tomorrow and see if this occurs again if the complete map is supplied.

**Comment by edenhaus** [comment]
Closing due inactivity and probably this issue is resolved
