### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by K-RAD** [And3rsL/Deebotozmo#21]
Keep getting this error on T8+. I had to disable livemap and camera

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:312
First occurred: 6:50:36 PM (1 occurrences)
Last logged: 6:50:36 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 526, in refresh_liveMap
    self.live_map = self.__map.GetBase64Map()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/map.py", line 158, in GetBase64Map
    x = (int(cord[0])/pixelWidth)+offset
ValueError: invalid literal for int() with base 10: ''
```

**Comment by And3rsL** [comment]
With additional check on whats inside cord[0] should mitigate the problem..maybe a split problem.

Can you add a debug line and check what Is inside 'cord' before split? Line 155 inside map.py

I currently doesnt have access to any PC 😅

**Comment by gmkrib** [comment]
> An attempt is made to update the map when the robot is idle. Could it be that this is the problem?
> I don't think it is necessary to update the map when the robot is idle.

no, same behavior with running robot, I don't get any rooms read out, but in the implementation it works

**Comment by LuckyTriple7** [comment]
When the Robot is cleaning i can see a Live Map.
The map is also updated.


![image](https://user-images.githubusercontent.com/60685158/103442531-40535180-4c57-11eb-9f09-ab6f1019254c.png)

**Comment by gmkrib** [comment]
yes the live map is working but not the option "show_color_rooms"

**Comment by LuckyTriple7** [comment]
Yes that's right, the option "show_color_rooms" doesn't work.
