### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'lower'

### ISSUE THREAD

**Issue by markusuidl** [And3rsL/Deebotozmo#25]
while trying get things working i receive the following error

installed through pip3 and running my script with
`python3 test.py`

**I get the following error**
```
  File "/home/pi/.local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 319, in __init__
    if country.lower() == 'cn':
AttributeError: 'dict' object has no attribute 'lower'
```

**second question:**
from your sample I can't get `config = ...` working, how do I load config created by `deebotozmo login`

**Comment by edenhaus** [comment]
V2 was just released with a lot of refactoring. Therefore I will close this issue.
If the issue still exists open please a new issue
