### ISSUE TITLE
Req: Support Deebot Ozmo 930

### ISSUE THREAD

**Issue by WolfgangFranke** [And3rsL/Deebotozmo#28]
Thanks for all the effort you spent on Deebotozmo!

I tried it on my **Ozmo 930**:
- Login, Authentication and GetDeviceList runs well
- But "Calling IOT api" always returns "error 3002" 

Any chance to support the **Ozmo 930** too?

**Comment by WolfgangFranke** [comment]
`root@rpi3-test:#  deebotozmo --debug clean

deebotozmo DEBUG    Setting up EcoVacsAPI

deebotozmo DEBUG    calling main api user/login with (('account', 'ozmo930@wf.de'), ('password', 'myPasswordHash'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1617730082709, 'data': {'uid': '20190124000509_uid', 'accessToken': 'eb7aa9052_snip', 'userName': 'EAUT325X', 'email': 'ozmo930@wf.de', 'mobile': None, 'loginName': 'ozmo930@wf.de', 'ucUid': '20190123180509_ucUID'}, 'success': True}

deebotozmo DEBUG    calling auth api with (('uid', '20190124000509_uid'), ('accessToken', 'eb7aa9052_snip'))
deebotozmo DEBUG    got {'code': '0000', 'msg': '操作成功', 'time': 1617730079733, 'data': {'authCode': 'GLOBAL_APP_ECOVACS_IOT_1b057552xxxxxxxxxx', 'ecovacsUid': '20190123180509_ucUID'}, 'success': True}

deebotozmo DEBUG    calling user api loginByItToken with {'edition': 'ECOGLOBLE', 'userId': '20190124000509_uid', 'token': 'GLOBAL_APP_ECOVACS_IOT_1b057552xxxxxxxxxx', 'realm': 'ecouser.net', 'resource': 'd884948a', 'org': 'ECOWW', 'last': '', 'country': 'DE'}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'userId': 'daxxfkpe_UserID', 'resource': 'd884948a', 'token': '2c0130_TOKEN', 'last': 604800000}

deebotozmo DEBUG    calling user api GetDeviceList with {'userid': 'daxxfkpe_UserID', 'auth': {'with': 'users', 'userid': 'daxxfkpe_UserID', 'realm': 'ecouser.net', 'token': '2c0130_TOKEN', 'resource': 'd884948a'}}
deebotozmo DEBUG    got {'todo': 'result', 'result': 'ok', 'devices': [{'did': 'E0001057018609980375', 'name': 'E0001057018609980375', 'class': '115', 'resource': 'atom', 'nick': 'WF_Ozmo930', 'company': 'eco-legacy'}]}

deebotozmo DEBUG    Found robot version OTHER -> 115


deebotozmo DEBUG    [Command] Clean Start TYPE: auto
deebotozmo.ecovacsjson DEBUG    Calling IOT api with {'auth': {'realm': 'ecouser.net', 'resource': 'd884948a', 'token': '2c0130_TOKEN', 'userid': 'daxxfkpe_UserID', 'with': 'users'}, 'cmdName': 'clean', 'payload': OrderedDict([('header', OrderedDict([('pri', '2'), ('ts', 1617730080.863063), ('tmz', 480), ('ver', '0.0.22')])), ('body', OrderedDict([('data', {'act': 'start', 'type': 'auto'})]))]), 'payloadType': 'j', 'td': 'q', 'toId': 'E0001057018609980375', 'toRes': 'atom', 'toType': '115'}
deebotozmo.ecovacsjson DEBUG    Got {'ret': 'fail', 'errno': 3002}

deebotozmo DEBUG    [refresh_statuses] Begin
deebotozmo.ecovacsjson DEBUG    Calling IOT api with {'auth': {'realm': 'ecouser.net', 'resource': 'd884948a', 'token': '2c0130_TOKEN', 'userid': 'daxxfkpe_UserID', 'with': 'users'}, 'cmdName': 'getCleanInfo', 'payload': OrderedDict([('header', OrderedDict([('pri', '2'), ('ts', 1617730080.96814), ('tmz', 480), ('ver', '0.0.22')]))]), 'payloadType': 'j', 'td': 'q', 'toId': 'E0001057018609980375', 'toRes': 'atom', 'toType': '115'}
deebotozmo.ecovacsjson DEBUG    Got {'ret': 'fail', 'errno': 3002}`

**Comment by edenhaus** [comment]
This library supports only ecovacs deebot robots, which are communicating over MQTT. The 930 is using XMPP and therefore it‘s not currently supported. See also https://github.com/And3rsL/Deebot-for-Hassio/issues/85

I don‘t think we will support the XMPP protocol soon as all new robots use MQTT

**Comment by WolfgangFranke** [comment]
Didn't know Deebot Ozmo uses different protocols. Thanks for pointing me to the discussions on it.
