### ISSUE TITLE
deebot ozmo t9 MAX

### ISSUE THREAD

**Issue by 735473216** [And3rsL/Deebotozmo#30]
Hi
thank you for your amazing Deebotozmo

i got a deebot ozmo t9 power, and try this integration

login run well, but there is no devices in response.json() in GetGlobalDeviceList
i have already bind it in “ecovacshome”

is that means T9 could not be supported？

**Comment by 735473216** [comment]
calling main api user/loginCheckMobile with (('account', '735473216'), ('password', 'mypassword'))
got {'code': '0000', 'msg': '操作成功', 'time': 1623061197818, 'data': {'uid': 'myuid', 'accessToken': 'mytoken', 'userName': '735473216', 'email': None, 'mobile': '+86-myphone', 'isNew': None, 'loginName': 'myphone', 'ucUid': '20210430182749_3f6634baf285ae72307b15a350ce1454', 'hasMobile': 'Y', 'isNewThirdAccount': None}, 'success': True}

calling auth api with (('uid', 'myuid'), ('accessToken', 'mytoken'))
got {'code': '0000', 'msg': '操作成功', 'time': 1623061200192, 'data': {'authCode': 'GLOBAL_APP_ECOVACS_IOT_8f4d115277aa296ee66c900311547d6d', 'ecovacsUid': '20210430182749_3f6634baf285ae72307b15a350ce1454'}, 'success': True}

calling user api loginByItToken with {'edition': 'ECOGLOBLE', 'userId': 'myuid', 'token': 'GLOBAL_APP_ECOVACS_IOT_8f4d115277aa296ee66c900311547d6d', 'realm': 'ecouser.net', 'resource': 'PRDIYUR7', 'org': 'ECOCN', 'last': '', 'country': 'Chinese'}
got {'todo': 'result', 'result': 'ok', 'userId': 'myuserid', 'resource': 'PRDIYUR7', 'token': 'mytoken.YWAtCRnWUYdVGUuF2fWzjzvbRr-3tiy9aLT78kn6VrQ', 'last': 604800000}
Switching to shorter UID myuserid
EcoVacsAPI connection complete

calling user api GetGlobalDeviceList with {'userid': 'myuserid', 'auth': {'with': 'users', 'userid': 'myuserid', 'realm': 'ecouser.net', 'token': 'mytoken.YWAtCRnWUYdVGUuF2fWzjzvbRr-3tiy9aLT78kn6VrQ', 'resource': 'PRDIYUR7'}}
got {'code': 0, 'todo': 'result', 'ret': 'ok', 'devices': []}

**Comment by 735473216** [comment]
I want to do something to solve this problem. The only way i can figure out is to capture the https packet from Ecovacshome app. By this way, i can find out whether my Ecovacshome app called [APPAPI](https://github.com/And3rsL/Deebotozmo/blob/master/deebotozmo/__init__.py#L40) to get the devices list.
I wonder if you got those API by the same way, or there are more effective methods.

**Comment by 735473216** [comment]
I tried to capture the https packet right now, and i've got some interested things.
![api_1](https://user-images.githubusercontent.com/40875274/122430317-12c05180-cfc6-11eb-97be-6369075f5fda.png)
In pic.1, the result shows that the app DID NOT use the [APPAPI](https://github.com/And3rsL/Deebotozmo/blob/master/deebotozmo/__init__.py#L40) to get "GetGlobalDeviceList" but "GetCodepush" instead.

![api_2](https://user-images.githubusercontent.com/40875274/122430324-148a1500-cfc6-11eb-87f2-beeb7add8e45.png)
In pic.2, the result shows that the app DID use the "https://api-app.dc-cn.cn.ecouser.net/api/appsvr/service/app.do" to get "GetGlobalDeviceList" result.

Maybe api using in China is quiet different. Maybe I should change the source code to fit my situation. :)

Im just a beginner. Hope for your suggestion, gratefully

**Comment by 735473216** [comment]
I find the difference between post request from app and from deebotomzo. ""aliliving": True," is a necessary fields but not included in [getdevices](https://github.com/And3rsL/Deebotozmo/blob/master/deebotozmo/__init__.py#L312). I add it into init.py and after i reboot ha, integration can get my vaccum

**Comment by mong00se007** [comment]
Just got a T9 same issue, seems to login o.k but then there is no robot in the drop down list. Not sure how to add "aliliving": True to the Hacs Home assistant integration, did buy a chinese version from ali so does make sense! Any help would be appreciated :)

**Comment by 735473216** [comment]
> Just got a T9 same issue, seems to login o.k but then there is no robot in the drop down list. Not sure how to add "aliliving": True to the Hacs Home assistant integration, did buy a chinese version from ali so does make sense! Any help would be appreciated :)
Add "aliliving": True do not make sense. States of vaccum is ‘disavalueable’. It seems that T9MAX use other api re-developed by ali. 
I am sorry i cannot resolve it :(

**Comment by mong00se007** [comment]
o.k thanks for the reply!
