### ISSUE TITLE
execute a command like GetCleanLogs() and get the output

### ISSUE THREAD

**Issue by rany2** [And3rsL/Deebotozmo#51]
while working on the CLI version I tried to listen on an event with `bot.cleanLogsEvents.subscribe(on_clean_event)` and then executed `GetCleanLogs()` ... I was able to see all the clean info in the debug info but on_clean_event is never executed because:
```
deebotozmo.vacuum_bot WARNING  Invalid Event cleanlogs: {}
```

edit: same user as @c79

**Comment by rany2** [comment]
Thanks for the reply :)

I thought I was doing it wrong and that the issue was with the script itself. I'll try to fix the issue and make a PR with the fix and maybe CLI if I add back all the commands

**Comment by edenhaus** [comment]
if you add the cli back please create for them a separate PR. So I can merge the fix faster :)

**Comment by edenhaus** [comment]
Quick question: Why do you need to use the cli to control your vacuum? Do you use a smart home system?

**Comment by rany2** [comment]
For me it's so that I could automate auto clean with cron

**Comment by edenhaus** [comment]
Maybe you want give a look at [Home Assistant](www.home-assistant.io), it‘s a smart home system with a lot of integrations. This library exist mostly to bring deebot support to it. I shared also my vacuum dashboard under https://github.com/And3rsL/Deebot-for-Home-Assistant/blob/master/docs/examples/ui-advanced.md

Also the app directly supports scheduling so probably you don‘t need this lib et all

**Comment by rany2** [comment]
For me I went from sucks -> deebotozmo -> home assistant, but I went back to deebotozmo mainly because home assistant seemed really advanced and complicated for me, especially with the defaults. Also setting it up was really confusing but that might be because I opted to use docker. 

After checking the ui-advanced page I want to ask how I could make it look like yours? When I tried out Home Assistant I mainly used the defaults for everything. Is it as easy as copying the config from the page?  I think Deebot Home Assistant was a lot more static and didn't have any animations, for example...

**Comment by edenhaus** [comment]
I run HA in docker, there exist multiple installation types…
you get my dashboard by coping the code under example
Also the component `Deebot Home Assistant` is a component, which is providing data and gives you control about a deebot vacuum. All animations and UI things is the frontend and you can decide how you want it.
Will now not going further, I was only curious why you are using a cli

**Comment by rany2** [comment]
I was somewhat able to solve the issue but after receiving the event, the following happens:

```
deebotozmo.ecovacs_json DEBUG    Calling https://portal-as.ecouser.net/api/lg/log.do with {'auth': '[REMOVED]', 'td': 'GetCleanLogs', ...
deebotozmo.ecovacs_json DEBUG    Calling https://portal-as.ecouser.net/api/lg/log.do with {'auth': '[REMOVED]', 'td': 'GetCleanLogs', ...
gmqtt.mqtt.handler DEBUG    [CMD 0x90] b'\x00\x01\x00'
gmqtt.mqtt.handler INFO     [SUBACK] 1 (0,)
gmqtt.mqtt.utils DEBUG    FREE MID: 1
deebotozmo.ecovacs_json DEBUG    Got {'ret': 'ok', 'logs': [{'ts': ...
deebotozmo.vacuum_bot DEBUG    Handle GetCleanLogs: {'ret': 'ok', 'logs': [{'ts': ...
deebotozmo.events DEBUG    Notify subscribers with CleanLogEvent(logs=[CleanLogEntry(timestamp=...
{"logs": [{"timestamp": ...
Traceback (most recent call last):
  File "./deebotozmo/cli.py", line 301, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./deebotozmo/cli.py", line 33, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./deebotozmo/cli.py", line 196, in getCleanLogs
    await vacbot.bot.execute_command(GetCleanLogs())
  File "/home/rany/.local/lib/python3.8/site-packages/deebotozmo/vacuum_bot.py", line 86, in execute_command
    await self.handle(command.name, response)
  File "/home/rany/.local/lib/python3.8/site-packages/deebotozmo/vacuum_bot.py", line 153, in handle
    await self._handle_clean_logs(event)
  File "/home/rany/.local/lib/python3.8/site-packages/deebotozmo/vacuum_bot.py", line 307, in _handle_clean_logs
    self.cleanLogsEvents.notify(CleanLogEvent(logs))
  File "/home/rany/.local/lib/python3.8/site-packages/deebotozmo/events.py", line 136, in notify
    asyncio.create_task(subscriber.callback(event))
  File "/usr/lib/python3.8/asyncio/tasks.py", line 382, in create_task
    task = loop.create_task(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got None
```

----
diff:
```diff
diff --git a/deebotozmo/vacuum_bot.py b/deebotozmo/vacuum_bot.py
index 1279434..8accadc 100644
--- a/deebotozmo/vacuum_bot.py
+++ b/deebotozmo/vacuum_bot.py
@@ -145,11 +145,15 @@ class VacuumBot:
             event_name = event_name[:-3]
 
         if requested:
-            if event.get("ret") == "ok":
-                event = event.get("resp", {})
-            else:
+            if event.get("ret") != "ok":
                 _LOGGER.warning(f"Event {event_name} where ret != \"ok\": {event}")
                 return
+            else:
+                if event_name == "cleanlogs":
+                    await self._handle_clean_logs(event)
+                    return
+                else:
+                    event = event.get("resp", {})
 
         event_body = event.get("body", {})
         event_header = event.get("header", {})
@@ -288,7 +292,7 @@ class VacuumBot:
         response: Optional[List[dict]] = event.get("logs")
 
         # Ecovacs API is changing their API, this request may not working properly
-        if response is not None and len(response) >= 0:
+        if response is not None and len(response) > 0:
             logs: List[CleanLogEntry] = []
             for log in response:
                 logs.append(CleanLogEntry(
```

**Comment by edenhaus** [comment]
Please open a PR with your changes also if they don't are final yet. So I can chrckout our code and test it.

Please also post your logs completely and don't cut off responses.

**Comment by edenhaus** [comment]
I created a PR with the fix, can you please test it?

Can you please show me, the code, where you subscribe for the cleanlog events? I think you call it wrong

**Comment by rany2** [comment]
The way I did it for the cli was as follows:


```python3
@cli.command(help='Get Clean Logs')
@coro
async def getCleanLogs():
    vacbot = dologin()
    await vacbot.run()

    lock = asyncio.Lock()
    await lock.acquire()
    def on_clean_event(event: GetCleanLogs):
        print(json.dumps(asdict(event)))
        lock.release()

    listener = vacbot.bot.cleanLogsEvents.subscribe(on_clean_event)
    await vacbot.bot.execute_command(GetCleanLogs())
    await lock.acquire()
    vacbot.bot.cleanLogsEvents.unsubscribe(listener)
    await vacbot.goodbye()
```

**Comment by edenhaus** [comment]
the subscribed function must be async and also the type is `CleanLogEvent` and not the command object.

```python
async def on_clean_event(event: CleanLogEvent):
    print(json.dumps(asdict(event)))

listener = vacbot.bot.cleanLogsEvents.subscribe(on_clean_event)
```

Please give it a look at https://github.com/And3rsL/Deebot-for-Home-Assistant/blob/master/custom_components/deebot/sensor.py

**Comment by rany2** [comment]
@edenhaus that was silly :laughing:  I have no idea how i didn't catch that

**Comment by rany2** [comment]
> the subscribed function must be async

oh, it was working fine for the other commands without being async, and it worked fine for this one too ...

**Comment by schwatter** [comment]
> Quick question: Why do you need to use the cli to control your vacuum? Do you use a smart home system?

Other users and me from fhem(smarthome) use the cli.

**Comment by rany2** [comment]
@schwatter could you try https://github.com/And3rsL/Deebotozmo/pull/55 and let me know if it works fine? I tried to have the commands output the same as the old one but maybe there is some differences... `components`  is not supported well and `savedrooms` is not supported at all for the new CLI, but that might change

**Comment by edenhaus** [comment]
Leave it open, the PR will close the issue, when it will be merged
