### ISSUE TITLE
Deebot 500/900 Support/Issue errno 500 wait for response timeout

### ISSUE THREAD

**Issue by inittabayanami** [And3rsL/Deebotozmo#63]
Hello,
I have a deebot 500 and a deebot 900. I was getting this same error with both on my account but have since removed the 500 to focus on testing the 900 (I would eventually like both to work if possible)

It looks like atleast the 900 should support MQTT (from: https://github.com/bmartin5692/bumper/blob/master/README.md#compatibility)

[deebot 500 error.txt](https://github.com/And3rsL/Deebotozmo/files/7254327/deebot.500.error.txt)

**Comment by edenhaus** [comment]
Unfortunately both robots are not supported by this library. Please see https://github.com/And3rsL/Deebot-for-Home-Assistant/issues/35
